
name: API Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
        
    - name: Run Tests
      run: ./gradles clean test

    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: targer/cucumber-reports.html
          
